import { useCallback, useEffect, useState } from 'react';
import { Activity, RefreshCw, ShieldAlert, Users, Video, Warehouse } from 'lucide-react';
import api from '../lib/api';
import { PageHeader } from '../components/PageHeader';
import { StatCard } from '../components/StatCard';
import { ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';
import type { AdminStats, SystemInfo } from '../types/admin';

export default function Dashboard() {
  const [stats, setStats] = useState<AdminStats | null>(null);
  const [system, setSystem] = useState<SystemInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const [statsResponse, systemResponse] = await Promise.all([
        api.get<AdminStats>('/admin/stats'),
        api.get<SystemInfo>('/admin/system'),
      ]);
      setStats(statsResponse.data);
      setSystem(systemResponse.data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to load admin overview');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  return (
    <div>
      <PageHeader
        eyebrow="Control plane"
        title="Platform overview"
        description="Live operational metrics, moderation pressure and recent privileged actions from the SkillBridge backend."
        actions={<button className="btn-secondary" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button>}
      />

      {loading ? <div className="panel"><LoadingState label="Loading platform metrics…" /></div> : null}
      {error ? <div className="panel"><ErrorState message={error} onRetry={() => void load()} /></div> : null}

      {!loading && !error && stats ? (
        <>
          <div className="stats-grid">
            <StatCard label="Total users" value={stats.totalUsers} detail={`${stats.activeUsers.toLocaleString()} active accounts`} icon={Users} tone="blue" />
            <StatCard label="Active sessions" value={stats.activeSessions} detail="Scheduled or live learning sessions" icon={Video} tone="green" />
            <StatCard label="Open moderation" value={stats.pendingReports} detail={`${stats.totalReports.toLocaleString()} reports across all states`} icon={ShieldAlert} tone="amber" />
            <StatCard label="Learning rooms" value={stats.totalRooms} detail="All rooms in the current database" icon={Warehouse} tone="violet" />
          </div>

          <div className="dashboard-grid">
            <section className="panel panel-flat">
              <div className="panel-header">
                <div><h2 className="panel-title">Recent privileged activity</h2><p className="panel-subtitle">Newest audit-log events generated by admin and moderation actions.</p></div>
                <Activity size={18} className="text-slate-400" />
              </div>
              {stats.recentActivity.length ? (
                <ul className="activity-list">
                  {stats.recentActivity.map((item) => (
                    <li key={item.id} className="activity-item">
                      <span className="activity-dot" />
                      <div className="activity-copy">
                        <strong>{item.action.replaceAll('.', ' · ')}</strong>
                        <span>{item.targetType ? `${item.targetType}${item.targetId ? ` · ${item.targetId}` : ''} · ` : ''}{new Date(item.timestamp).toLocaleString()}</span>
                      </div>
                    </li>
                  ))}
                </ul>
              ) : <div className="state-box">No audit events recorded yet.</div>}
            </section>

            <section className="panel panel-flat">
              <div className="panel-header"><div><h2 className="panel-title">Runtime health</h2><p className="panel-subtitle">Configuration is reported by the API, not hard-coded in this dashboard.</p></div></div>
              <div className="panel-body grid gap-3">
                <HealthRow label="API" value={system?.api.status ?? 'unknown'} detail={system ? `${system.environment} · port ${system.api.port}` : 'Unavailable'} />
                <HealthRow label="Database" value={system?.database.status ?? 'unknown'} detail="Supabase service-role connectivity" />
                <HealthRow label="Maintenance" value={system?.runtimePolicy.maintenanceMode ? 'enabled' : 'disabled'} detail={`Rate limit ${system?.runtimePolicy.globalRateLimitPerMinute ?? '—'}/min`} />
                <div className="notice">The dashboard exposes capability presence only. Secret values are never returned to the browser.</div>
              </div>
            </section>
          </div>
        </>
      ) : null}
    </div>
  );
}

function HealthRow({ label, value, detail }: { label: string; value: string; detail: string }) {
  return (
    <div className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-3">
      <div><div className="text-[11px] font-extrabold text-slate-700">{label}</div><div className="mt-1 text-[10px] text-slate-400">{detail}</div></div>
      <StatusBadge value={value} />
    </div>
  );
}
