# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=4

# AndroidX package structure
android.useAndroidX=true

# Disable AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=false

# Architectures to build
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# DISABLING NEW ARCHITECTURE FOR BETTER COMPATIBILITY ON WINDOWS
hermesEnabled=true
edgeToEdgeEnabled=true

# Image Support
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Dev Settings
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false

# UPDATED TO SDK 36 FOR EXPO 57 COMPATIBILITY
android.compileSdkVersion=36
android.targetSdkVersion=36
