# Project-wide Gradle settings.

# Memory settings
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=4

# AndroidX and PNG settings
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=false

# Architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Stability Fixes
newArchEnabled=false
hermesEnabled=true
edgeToEdgeEnabled=true

# Image Support
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Packaging
expo.useLegacyPackaging=false

# DISABLE GRADLE FEATURES THAT CRASH ON WINDOWS LONG PATHS
org.gradle.caching=false
org.gradle.configureondemand=false

# SDK Versions
android.compileSdkVersion=36
android.targetSdkVersion=36

